version: "3.8"

services:
  mysql:
    container_name: mysql_nodejs_arch
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - "3307:3306"
    command: --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql
    environment:
      MYSQL_DATABASE: ada_db
      MYSQL_ROOT_PASSWORD: secret